<a href="https://colab.research.google.com/github/yiding2022/DAAI/blob/main/NN_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from dmba import classificationSummary

ModuleNotFoundError: No module named 'dmba'

In [ ]:
!pip install dmba

Collecting dmba
  Downloading dmba-0.2.4-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.11/dist-packages (from dmba) (0.20.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from dmba) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from dmba) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from dmba) (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from dmba) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from dmba) (1.13.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->dmba) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->dmba) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->dmba) (4.55.8)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->dmba) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->dmba) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->dmba) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->dmba) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->dmba) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->dmba) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->dmba) (2025.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->dmba) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->dmba) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->dmba) (1.17.0)
Downloading dmba-0.2.4-py3-none-any.whl (11.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 67.7 MB/s eta 0:00:00
Installing collected packages: dmba
Successfully installed dmba-0.2.4

The cheese case

In [ ]:
# Let's start the example discussed in lecture

data = {'Obs.': [1, 2, 3, 4, 5, 6],
    'Fat': [0.2, 0.1, 0.2, 0.2, 0.4, 0.3],
    'Salt': [0.9, 0.1, 0.4, 0.5, 0.5, 0.8],
    'Acceptance': ['like', 'dislike', 'dislike', 'dislike', 'like', 'like']}

df = pd.DataFrame(data)
df

   Obs.  Fat  Salt Acceptance
0     1  0.2   0.9       like
1     2  0.1   0.1    dislike
2     3  0.2   0.4    dislike
3     4  0.2   0.5    dislike
4     5  0.4   0.5       like
5     6  0.3   0.8       like

In [ ]:
# define the feature set and the target set

X = df[['Fat', 'Salt']]
y = df['Acceptance']

In [ ]:
classes = sorted(y.unique())
classes

['dislike', 'like']

In [ ]:
# construct a neural network with a single hidden layer with 3 nodes

clf = MLPClassifier(hidden_layer_sizes=(3), activation='logistic', solver='lbfgs', random_state=1)

# fit the model to the data and predict the target values
clf.fit(X, y)
clf.predict(X)

array(['like', 'dislike', 'dislike', 'dislike', 'like', 'like'],
      dtype='<U7')

In [ ]:
# Network structure and estimated weights
print('Intercepts')
print(clf.intercepts_)
print('Weights')
print(clf.coefs_)

# Prediction
print(pd.concat([df,pd.DataFrame(clf.predict_proba(X), columns=classes)], axis=1))

Intercepts
[array([0.13368042, 4.07247549, 7.00768105]), array([14.3074867])]
Weights
[array([[ -1.3065648 ,  -4.20427797, -13.29587331],
       [ -0.04399729,  -4.91606921,  -6.03356987]]), array([[ -0.27348314],
       [ -9.01211576],
       [-17.63504684]])]
   Obs.  Fat  Salt Acceptance   dislike      like
0     1  0.2   0.9       like  0.000490  0.999510
1     2  0.1   0.1    dislike  0.999994  0.000006
2     3  0.2   0.4    dislike  0.999741  0.000259
3     4  0.2   0.5    dislike  0.997368  0.002632
4     5  0.4   0.5       like  0.002133  0.997867
5     6  0.3   0.8       like  0.000075  0.999925

In [ ]:
epochs = clf.n_iter_
print("Number of epochs:", epochs)

Number of epochs: 34

A new dataset

In [ ]:
# Let’s apply the network training process to some real data: US automobile accidents that have been classified by their level of severity as no injury, injury,
# or fatality. A firm might be interested in developing a system for quickly classifying the severity of an accident, based on initial reports and associated
# data in the system (some of which rely on GPS-assisted reporting). Such a system could be used to assign emergency response team priorities.

In [ ]:
from google.colab import files

# Upload file
uploaded = files.upload()

Saving accidentsnn.txt to accidentsnn.txt

In [ ]:
# Extract the file name
file_name = list(uploaded.keys())[0]

# Load the file into a Pandas DataFrame
accidents_df = pd.read_csv(file_name)

In [3]:
url = "https://raw.githubusercontent.com/yiding2022/DAAI/main/accidentsnn.txt"
accidents_df = pd.read_csv(url)

In [4]:
accidents_df

     ALCHL_I  PROFIL_I_R  SUR_COND  VEH_INVL  MAX_SEV_IR
0          2           0         1         1           0
1          2           1         1         1           2
2          1           0         1         1           0
3          2           0         2         2           1
4          2           1         1         2           1
..       ...         ...       ...       ...         ...
994        2           0         1         1           0
995        2           0         1         1           0
996        1           1         1         2           1
997        1           0         1         3           2
998        2           0         1         1           0

[999 rows x 5 columns]

In [ ]:
# read data

# accidents_df = pd.read_csv('accidentsnn.csv')
accidents_df.SUR_COND = accidents_df.SUR_COND.astype('category')
accidents_df.MAX_SEV_IR = accidents_df.MAX_SEV_IR.astype('category')

In [ ]:
accidents_df
# ALCHL_I Presence (1) or absence (2) of alcohol
# PROFIL_I_R Profile of the roadway: level (1), other (0)
# SUR_COND Surface condition of the road: dry (1), wet (2), snow/slush (3), ice (4), unknown (9)
# VEH_INVL Number of vehicles involved
# MAX_SEV_IR Presence of injuries/fatalities: no injuries (0), injury (1), fatality (2) - outcome variable

     ALCHL_I  PROFIL_I_R SUR_COND  VEH_INVL MAX_SEV_IR
0          2           0        1         1          0
1          2           1        1         1          2
2          1           0        1         1          0
3          2           0        2         2          1
4          2           1        1         2          1
..       ...         ...      ...       ...        ...
994        2           0        1         1          0
995        2           0        1         1          0
996        1           1        1         2          1
997        1           0        1         3          2
998        2           0        1         1          0

[999 rows x 5 columns]

In [ ]:
# convert the categorical data into dummy variables
# exclude the column for SUR_COND 9 = unknown
processed = pd.get_dummies(accidents_df, columns=['SUR_COND'])
processed = processed.drop(columns=['SUR_COND_9'])
outcome = 'MAX_SEV_IR'
predictors = [c for c in processed.columns if c != outcome]

In [ ]:
processed

,ALCHL_I,PROFIL_I_R,VEH_INVL,MAX_SEV_IR,SUR_COND_1,SUR_COND_2,SUR_COND_3,SUR_COND_4
0,2,0,1,0,True,False,False,False
1,2,1,1,2,True,False,False,False
2,1,0,1,0,True,False,False,False
3,2,0,2,1,False,True,False,False
4,2,1,2,1,True,False,False,False
...,...,...,...,...,...,...,...,...
994,2,0,1,0,True,False,False,False
995,2,0,1,0,True,False,False,False
996,1,1,2,1,True,False,False,False
997,1,0,3,2,True,False,False,False
998,2,0,1,0,True,False,False,False

In [ ]:
predictors

['ALCHL_I',
 'PROFIL_I_R',
 'VEH_INVL',
 'SUR_COND_1',
 'SUR_COND_2',
 'SUR_COND_3',
 'SUR_COND_4']

In [ ]:
# partition data
X = processed[predictors]
y = processed[outcome]
train_X, valid_X, train_y, valid_y = train_test_split(X, y, test_size=0.4, random_state=1)

In [ ]:
# train neural network with 2 hidden nodes
clf = MLPClassifier(hidden_layer_sizes=(7), activation='logistic', solver='lbfgs', random_state=1)
clf.fit(train_X, train_y.values)

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

MLPClassifier(activation='logistic', hidden_layer_sizes=7, random_state=1,
              solver='lbfgs')

In [ ]:
# training performance (use idxmax to revert the one-hot-encoding)
classificationSummary(train_y, clf.predict(train_X))
# validation performance
classificationSummary(valid_y, clf.predict(valid_X))

# We see that classes 0 and 1
# are perfectly classified in both the training and validation data. However, class 2 has a high rate of misclassification.

Confusion Matrix (Accuracy 0.8748)

       Prediction
Actual   0   1   2
     0 332   0   0
     1   0 175   5
     2  31  39  17
Confusion Matrix (Accuracy 0.8575)

       Prediction
Actual   0   1   2
     0 218   0   1
     1   1 113   5
     2  24  26  12

In [ ]:
print('Intercepts')
print(clf.intercepts_)
print('Weights')
print(clf.coefs_)
print('# of Epochs:', clf.n_iter_)

Intercepts
[array([ 4.97086004, -1.59972439,  2.91448316,  6.2244812 , -0.3724809 ,
        0.49507272, -4.55152708]), array([-10.71339095,   8.97801874,   2.02568176])]
Weights
[array([[ -0.3908231 ,  -0.72298631,   3.42043871,  -5.28033251,
         -1.5674941 ,  -0.321741  ,  -3.69511188],
       [-14.47123544,  -9.1051418 ,  -9.54838866,  -3.20220785,
         -5.49380777,   1.34357285,  -1.22978381],
       [ -0.67634324, -10.55584465,  -6.86863263,  -3.81554418,
         -5.56361955,   0.13730967,  -5.38847552],
       [ -2.24565798,   6.0448905 ,   5.93858887,   3.5191979 ,
          4.64281766,  -1.7553116 ,  -1.22548232],
       [ -4.69574275,  -5.44632957,  -6.80360512,  -7.17142068,
         -3.40288909,  -2.14207681,  -0.38635705],
       [ -3.7284936 ,  -0.27122432,  -0.18714011,  -0.71940299,
         -0.06219922,  -7.93275858,   0.33089172],
       [-15.75358603,  -0.84030906,  -8.40522991,   4.42679628,
         -0.47653114,  -1.88437444,   0.11059478]]), array([[ 12.63642398, -15.86098984,   3.05626106],
       [ -4.67512259,   5.44345988,  -1.01997782],
       [  7.63028102,  -5.29983403,  -2.63316532],
       [  2.30026995,  -7.14311719,   5.03307741],
       [  2.01003294,  -2.45843071,   1.27689901],
       [ -3.95016288,  -4.95256653,   8.53406219],
       [-12.01792817,   6.71375908,   5.29578225]])]
# of Epochs: 200

Avoid overfitting

In [ ]:
# let's limit the number of epochs to 100

clf = MLPClassifier(hidden_layer_sizes=(7), activation='logistic', solver='lbfgs', random_state=1, max_iter=100)
clf.fit(train_X, train_y.values)

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

MLPClassifier(activation='logistic', hidden_layer_sizes=7, max_iter=100,
              random_state=1, solver='lbfgs')

In [ ]:
# training performance (use idxmax to revert the one-hot-encoding)
classificationSummary(train_y, clf.predict(train_X))
# validation performance
classificationSummary(valid_y, clf.predict(valid_X))

# performance on validation data improved, but the performance on the training data is similar.

Confusion Matrix (Accuracy 0.8765)

       Prediction
Actual   0   1   2
     0 331   0   1
     1   0 172   8
     2  30  35  22
Confusion Matrix (Accuracy 0.8700)

       Prediction
Actual   0   1   2
     0 218   0   1
     1   1 114   4
     2  24  22  16